### ISSUE TITLE
JDO @Join relationships not persisted

### ISSUE THREAD

**Issue by dhakehurst** [datanucleus/datanucleus-neo4j#27]
I have two classes, as below.

When I store (makePersistent) an instance of the container,
the items do not get persisted.

This works fine with datanucleus-rdbms

@PersistenceCapable
class Container {
	@PrimaryKey
	@Persistent
	public String getIdentity() {...}

	@Persistent(defaultFetchGroup = "true")
	@Join
	public List<Item> getItems() {...}
}

@PersistenceCapable
class Item {
	@PrimaryKey
	@Persistent
	public String getIdentity() {...}
}

**Comment by andyjefferson** [comment]
What you're expecting there I've no idea. See the documentation for what is persisted
http://www.datanucleus.org/products/accessplatform_5_1/datastores/datastores.html#neo4j

Indeed Node  + Relationship + Node **are** persisted, and they are read back in on getObjectById or query operations (in all of my tests). 

There is no such concept of a "join table" supported so putting @Join makes no difference to anything. If you mean you want to contribute some support for persisting @Join in some other way then this is where you link your pull requests

**Comment by dhakehurst** [comment]
see
http://www.datanucleus.org/products/accessplatform_4_1/jdo/orm/one_to_many_list.html
1 to N relationships are either by Foreign-Key or Join Table

I was using and rdbms before switching to Neo4j.
JDO is supposed to mean I don't need to know what type of db is being used.
So the same JDO annotated classes should be useable irrespective of the db type.
Yes ?

Maybe the 'Join' is not necessary for Neo4j, but it does seem to be needed for RDBMS.

**Comment by andyjefferson** [comment]
The JDO spec contains some ORM aspects (that apply to RDBMS only), and some that are general. The JDO spec doesn't make a clear definition of how they should be applied because every database is different. The ORM aspects of the spec always apply to RDBMS, that part is defined in the JDO spec, but they do not always apply to "NoSQL". If you wanted to define some of what applies to NoSQL, you go to https://issues.apache.org/jira/browse/JDO-651

With current DN handling you don't need to know what type of DB is being used. It persists objects to Neo4j irrespective of what you put for @Join, and just ignores that metadata. There is nothing in the JDO spec that says you should invent some intermediate object (a Node in Neo4j), and then have a Relationship from A to A_B, and then a Relationship from A_B to B. That is what RDBMS *requires*.

**Comment by dhakehurst** [comment]
Still doesn't explain why the second object is not persisted.

Please re open and I will create a test case

**Comment by andyjefferson** [comment]
Did you read the link i gave? If I have an object A with a collection of B's it persist all objects as Nodes, and has Relationship objects between them.

**Comment by dhakehurst** [comment]
Yes, of course read it!

I will create a test case and make a new issue seeing as it has nothing to do with the Join annotation
